
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 25 14:17:59 CET 2025
//----------------------------------------------------

package com.kosta.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 46;
  public static final int MAP = 8;
  public static final int LTE = 42;
  public static final int CONST = 4;
  public static final int POSTINC = 19;
  public static final int LPAREN = 31;
  public static final int SEMI = 30;
  public static final int CONTINUE = 13;
  public static final int INTERFACE = 6;
  public static final int MINUS = 20;
  public static final int RPAREN = 32;
  public static final int AND = 43;
  public static final int LT = 38;
  public static final int OR = 44;
  public static final int COMMA = 29;
  public static final int CLASS = 5;
  public static final int DIV = 23;
  public static final int PLUS = 18;
  public static final int IF = 11;
  public static final int LSQBRACE = 35;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int EQUAL = 27;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 45;
  public static final int MOD = 24;
  public static final int NEQ = 40;
  public static final int IDENT = 48;
  public static final int BREAK = 14;
  public static final int VOID = 17;
  public static final int EQ = 39;
  public static final int GTE = 41;
  public static final int POSTDEC = 21;
  public static final int UNION = 26;
  public static final int LBRACE = 33;
  public static final int ELSE = 12;
  public static final int READ = 16;
  public static final int WHILE = 10;
  public static final int RBRACE = 34;
  public static final int EXTENDS = 7;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 47;
  public static final int RSQBRACE = 36;
  public static final int GT = 37;
  public static final int PRINT = 15;
  public static final int DO = 9;
}

